kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

permalink: /:title/

include:
  - _redirects

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - serve



