backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: /assets/files

collections:
  - name: "post"
    label: "Post"
    folder: "_posts"
    sort: "date:desc"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mm:ss"}
      - {label: "Image 1", name: "image1", widget: "image", required: false }
      - {label: "Image 2", name: "image2", widget: "image", required: false }
      - {label: "Image 3", name: "image3", widget: "image", required: false }
      - {label: "Image 4", name: "image4", widget: "image", required: false }
      - {label: "Body", name: "body", widget: "markdown"}
